name: Daily Job

on:
  schedule:
    - cron: "0 3 * * *"  #11:00
    - cron: "50 12 * * *"   #20:00  
  workflow_dispatch:

jobs:
  run-script:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2
      
    - name: Install Dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y yt-dlp sed nmap

    - name: Create speedtest directory
      run: mkdir -p speedtest

    - name: List speedtest directory
      run: ls -lR speedtest
    
    - name: Download files to speedtest directory
      run: |
        # 定义变量
        REPO="${{ secrets.ORIGIN_NAME }}/wods"
        BRANCH="main"
        DIR="speedtest"
        API_URL="https://api.github.com/repos/$REPO/contents/$DIR?ref=$BRANCH"

        # 从 GitHub API 获取文件列表
        curl -s $API_URL | jq -r '.[] | select(.type=="file") | .download_url' | while read -r file_url; do
          # 提取文件名并下载
          file_name=$(basename "$file_url")
          curl -L -o "speedtest/$file_name" "$file_url"
        done

    - name: Commit and push speedtest changes
      run: |
        git add speedtest/*
        git status
        git commit -m "Update speedtest files" || echo "No changes to commit"
        git pull origin main --rebase
        git push
      env:
        PAT: ${{ secrets.GITHUBS_TOKEN }}
      
    - name: Run Multitest Script
      #working-directory: iptv/speedtest
      run: |
        cd $GITHUB_WORKSPACE/speedtest
        bash ./multi_test.sh
      
    - name: Update Results
      run: |
        cd $GITHUB_WORKSPACE/speedtest
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git add .
        git commit -m "Update results"
        git push

    - name: Trigger Project B Workflow
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUBS_TOKEN }}
      run: |
        curl -X POST \
          -H "Accept: application/vnd.github.everest-preview+json" \
          -H "Authorization: token $GITHUB_TOKEN" \
          https://api.github.com/repos/${{ github.actor }}/wods/dispatches \
          -d '{"event_type":"trigger-wods"}'
