name: Daily Job

on:
  schedule:
    - cron: "10 20 * * *"
  workflow_dispatch:

jobs:
  run-script:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2
      
    - name: Install Dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y yt-dlp sed nmap
      
    - name: Run Multitest Script
      #working-directory: iptv/speedtest
      run: |
        cd $GITHUB_WORKSPACE/speedtest
        bash ./multi_test.sh
      
    - name: Update Results
      run: |
        cd $GITHUB_WORKSPACE/speedtest
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git add .
        git commit -m "Update results"
        git push

    - name: Debug PAT
      uses: actions/github-script@v4
      with:
        script: |
          const token = process.env.GITHUBS_TOKEN;
          const octokit = require('@octokit/rest')({
            auth: `token ${token}`
          });
          const { data: user } = await octokit.users.getAuthenticated();
          console.log(`Authenticated as ${user.login}`);
          
    - name: Trigger Project wods Workflow
      uses: peter-evans/repository-dispatch@v1
      with:
        token: ${{ secrets.GITHUBS_TOKEN }}
        repository: welvico/wods
        event-type: trigger-wods
