name: Daily Job

on:
  schedule:
    - cron: "0 3 * * *"  #11:00
    - cron: "0 12 * * *"   #20:00  
  workflow_dispatch:

jobs:
  run-script:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v3
      
    - name: Install Dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y yt-dlp sed nmap

    - name: Set Git Identity
      run: |
        git config --global user.email "actions@github.com"
        git config --global user.name "GitHub Actions"
      
    - name: Delete speedtest Folder
      run: |
        if [ -d "speedtest/" ]; then
          rm -rf speedtest/
          git rm -r --cached speedtest/
          git commit -m "Delete speedtest folder" || echo "No changes to commit"
          git push
        else
          echo "speedtest/ directory not found, skipping deletion"
        fi
      env:
        PAT: ${{ secrets.GITHUBS_TOKEN }}
    
    - name: Create speedtest directory
      run: mkdir -p speedtest

    - name: List speedtest directory
      run: ls -lR speedtest
    
    - name: Download files to speedtest directory
      run: |
        # 定义变量
        REPO="${{ secrets.ORIGIN_NAME }}/dszb"
        BRANCH="main"
        DIR="speedtest"
        API_URL="https://api.github.com/repos/$REPO/contents/$DIR?ref=$BRANCH"
        
        # 打印 API_URL 以调试
        echo "API URL: $API_URL"
        
        # 递归下载目录及其子目录
        download_directory() {
          local dir="$1"
          local api_url="https://api.github.com/repos/$REPO/contents/$dir?ref=$BRANCH"
    
          # 从 GitHub API 获取目录内容
          response=$(curl -s "$api_url")
          
          # 打印响应以调试
          echo "API response for $dir: $response"
        
          # 解析 JSON 响应并下载文件
          echo "$response" | jq -r '.[] | select(.type=="file") | .download_url' | while read -r file_url; do
            file_name=$(basename "$file_url")
            echo "Downloading file $file_name from $file_url"
            curl -L -o "$dir/$file_name" "$file_url"
          done
        
          # 处理子目录
          echo "$response" | jq -r '.[] | select(.type=="dir") | .path' | while read -r subdir; do
            mkdir -p "$subdir"
            echo "Processing subdirectory $subdir"
            download_directory "$subdir"
          done
        }
    
        # 创建根目录
        mkdir -p "$DIR"
    
        # 下载目录及其所有内容
        download_directory "$DIR"
    
    - name: Commit and push speedtest changes
      run: |
        git add speedtest
        git status
        git commit -m "Update speedtest files" || echo "No changes to commit"
        git pull origin main --rebase
        git push
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUBS_TOKEN }}

      
    - name: Run Multitest Script
      #working-directory: iptv/speedtest
      run: |
        cd $GITHUB_WORKSPACE/speedtest
        bash ./multi_test.sh
      
    - name: Update Results
      run: |
        cd $GITHUB_WORKSPACE/speedtest
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git add .
        git commit -m "Update results" || echo "No changes to commit"
        git pull --rebase
        git push
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUBS_TOKEN }}


    - name: Trigger Project B Workflow
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUBS_TOKEN }}
      run: |
        curl -X POST \
          -H "Accept: application/vnd.github.everest-preview+json" \
          -H "Authorization: token $GITHUB_TOKEN" \
          https://api.github.com/repos/${{ github.actor }}/wods/dispatches \
          -d '{"event_type":"trigger-wods"}'
